### PR TITLE
2018

### PR DESCRIPTION
**Pull request by mccullochk**
screen shot 2018-10-09 at 2 32 26 pm

### CODE REVIEW

**Comment by mccullochk** [comment]
@chadfawcett, could you take a quick look at the resources just to verify they all still make sense for this years event please?

**Comment by chadfawcett** [comment]
Looks good! We could keep the version checker as part of the local packages.

* https://github.com/chadfawcett/docker-npm-version-check

If Stephanie is able to attend we could add some of the rOpenSci projects, but not necessary before merging this branch in.

**Comment by chadfawcett** [comment]
Maybe add our express middleware repo since they're a super easy one in there. https://github.com/TwoStoryRobot/express-joi-middleware

Unless you want that for yourself haha. Then don't add it.

**Comment by mccullochk** [comment]
@chadfawcett, I already talked to Stephanie and she is not able to attend this year that's why I removed the rOpenSci projects.

**Comment by mccullochk** [comment]
I've also asked Fran if there are any students that have packages that they'd like to add to the list. It's probably unlikely but if they do we can always add those in later.

**Comment by chadfawcett** [comment]
Ah okay, thanks!

**Pull request merged**
